### ISSUE TITLE
Just a thanks!

### ISSUE THREAD

**Issue by BrettFraley** [rustygreen/ng-supabase#1]
@rustygreen - I literally just started building the same concept for an ng - supase package and found your repository, thank you for putting this work together!

I'm building a large project in Angular17 and the supabase-js library is a bit painful, out of date, and lacking in solid documentation for Angular clients.

**Comment by rustygreen** [comment]
Thanks for the note, @BrettFraley! What UI library do you intend on using (PrimeNG, Material, Bootstrap, other)? Let me know any pain points you find with this library as you start working with it, I'm still working towards a 1.0.0 release.

Thanks!
